Update index.html
htmlacademy-htmlcss/1892993-sedona-35 pull request #2
Opened 2022-09-27 20:10 UTC by WhiteShark23

Шапка сайта

2022-10-01 15:20 UTC, nisven requested changes

2022-10-01 15:20 UTC, nisvem commented on index.html
> +      <a href="index.html">Логотип</a>
В ссылках, где у тебя нет точного адреса, лучше использовать "#" это по сути означает, ссылка на ту же самую страницу, что сейчас. Почти всегда это временный вариант и его обычно потом заменяют на какой-то более рабочий вариант, но как заплатку используют его. 
Т.е. если пока ты не знаешь какую ссылку бы поставить и не знаешь куда она будет ввести, то лучше использовать его. У тебя будет href="#"

2022-10-01 15:20 UTC, nisvem commented on index.html
> +          <a class="navigation-link" href="index.html">Главная</a>
1) Тут можно убрать атрибут href, т.к. ссылка должна вести сама на себя. 
https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03:~:text=%D0%A3%C2%A0%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%20href.%20%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5%20%D0%B2%D0%B5%D0%B4%D1%83%D1%82%20%D0%BD%D0%B0%C2%A0%D1%81%D0%B0%D0%BC%D0%B8%D1%85%20%D1%81%D0%B5%D0%B1%D1%8F%2C%20%D0%BC%D0%BE%D0%B3%D1%83%D1%82%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B1%D0%B5%D0%B7%20%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%B0.

2) Тут также лучше будет добавить еще один класс. Один класс у тебя обозначает, что это ссылка "navigation-link" и второй класс добавить, который будет обозначать, что это ссылка страницы на которой ты находишься "navigation-link-current"
Почему используется два тире

Итого у тебя тут будет class="navigation-link navigation-link-current"

2022-10-01 15:20 UTC, nisvem commented on index.html
> +          <a class="navigation-link" href="index.html">О седоне</a>
Также href="#"
 Это не ошибка, а просто рекомендация.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +          <a class="navigation-link" href="index.html">Гостиницы</a>
Также href="#"
 Это не ошибка, а просто рекомендация.

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +      <a href="index.html">Логотип</a>
Также href="#"
 Это не ошибка, а просто рекомендация.

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +          <a class="navigation-link" href="index.html">Главная</a>
Также href="#"
 Это не ошибка, а просто рекомендация.

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +          <a class="navigation-link" href="index.html">О седоне</a>
Также href="#"
 Это не ошибка, а просто рекомендация.

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +          <a class="navigation-link-current" href="index.html">Гостиницы</a>
1) Тут аналогично с главной. По идее Гостинцы это и есть страница каталога и тут лучше убрать href. 
https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03:~:text=%D0%A3%C2%A0%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%20href.%20%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5%20%D0%B2%D0%B5%D0%B4%D1%83%D1%82%20%D0%BD%D0%B0%C2%A0%D1%81%D0%B0%D0%BC%D0%B8%D1%85%20%D1%81%D0%B5%D0%B1%D1%8F%2C%20%D0%BC%D0%BE%D0%B3%D1%83%D1%82%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%B1%D0%B5%D0%B7%20%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%B0.

2) Тут также лучше будет добавить еще один класс. Один класс у тебя обозначает, что это ссылка "navigation-link" и второй класс добавить, который будет обозначать, что это ссылка страницы на которой ты находишься "navigation-link-current"

Итого у тебя тут будет class="navigation-link navigation-link-current"

2022-10-01 15:20 UTC, nisvem commented on index.html
> +      <ul class="navigation-list navigation-user">
Тут для элементов лучше выбрать другой класс. 
Лучше для ul использовать, к примеру, header-list
Для li header-item и header-link для ссылок

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +      <ul class="navigation-list navigation-user">
Тут для элементов лучше выбрать другой класс.
Лучше для ul использовать, к примеру, header-list
Для li header-item и header-link для ссылок

navigation-user можно пока убрать. Если потребуется добавить классы - добавить не проблема)

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +      <header class="inner-header-title">
1) header используется только для шапки страницы, в main его использовать лучше не надо. Тут просто замени на div или мб section. 

2) И в классах title лучше использовать непосредственно для Названий страниц, а не для общих блоков. Тут просто замени класс на search-banner, например

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +        <h1 class="sedona-hotels">Гостиницы Седоны</h1>
Вот тут как раз можно в классах использовать title, можно просто заменить класс на title

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +        <a href="index.html"></a>
Здесь эти 2 ссылки - по сути это хлебные крошки (breadcrumb) и их лучше объединить в один блок.
Тут можно использовать ul - breadcrumb-list, li - breadcrumb-item и a - breadcrumb-link

2022-10-01 15:20 UTC, nisvem commented on catalog.html
> +        <fieldset class="catalog-filter-group">
Тут я сейчас приведу пример, как сделать лучше и правильнее. Дело в том, что input очень сложно визуализировать, поэтому используют label и связывают их id, а сам input просто скрывают. Вот как лучше сделать.
```

<fieldset class="infrastructure-filter-group">
          <legend class="infrastructure-filter-title">Инфраструктура:</legend>
          <ul class="infrastructure-filter-list">
            <li class="infrastructure-filter-item">
              <input class="visually-hidden filter-checkbox" id="checkbox-pool" type="checkbox" name="swimming-pool" checked>
              <label class="checkbox-label" for="checkbox-pool">
                Бассейн
              </label>
            </li>
            <li class="infrastructure-form-item">
              <input class="visually-hidden filter-checkbox" id="checkbox-parking" type="checkbox" name="parking">
              <label class="checkbox-label" for="checkbox-parking">
                Парковка
              </label>
            </li>
            <li class="infrastructure-form-item">
              <input class="visually-hidden filter-checkbox" id="checkbox-wifi" type="checkbox" name="Wi-Fi">
              <label class="checkbox-label" for="checkbox-wifi">
                Wi-Fi
              </label>
            </li>
          </ul>
        </fieldset>
```

2022-10-01 15:20 UTC, nisvem commented on index.html
> +      <h1 class="visually-hidden">Седона</h1>
h1 и img лучше тоже обернуть в блок section с классом banner, например

2022-10-01 15:20 UTC, nisvem commented on index.html
> +            <img src="" alt="Дом на фоне гор" class="Benefits-image">
Картинки лучше заносить к какой-то карточке, отдельно их не стоит выносить.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +            <img src="" alt="Каньон" class="canyon">
Тут тоже картинки лучше заносить к какой-то карточке, отдельно их не стоит выносить.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +           <h3 class="house">Жильё</h3>
Тут лучше для h3 использовать один класс. Например - availability-title. А картинку просто поместить img перед заголовком. 
Или добавить к availability-item еще один класс, показывающий уникальность элемента, к примеру - "availability-item availability-item-house"

2022-10-01 15:20 UTC, nisvem commented on index.html
> +           <p class="availability-house">Рекомендуем пожить в настоящем мотеле,
Тут также лучше использовать один класс availability-text

2022-10-01 15:20 UTC, nisvem commented on index.html
> +        <b class="hotel-search-item">Заинтересовались?</b>
Тег b лучше не использовать, на самом деле. Его можно заменить на p, и по классу добавить жирность. А вообще тут можно использовать h3, думаю это не будет ошибкой, т.к. это по сути заголовок секции.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +        <span>Укажите предполагаемые даты поездки,и мы покажем вам лучшие предложения гостиниц в Седоне</span>
Тут вместо span лучше использовать p. 

Отличие span и p в том, что span это строчный элемент, а p блочный. p можно использовать как блок с текстом, а span чаще всего используют для того, чтобы в тексте выделить что-то. 

Т.е. чаще всего это выглядит так. 

```
<p>
Укажите предполагаемые даты поездки, и мы <span>покажем вам</span> лучшие предложения гостиниц в Седоне
</p>
```

Тут обычно вешают на span класс и всячески стилизуют выделенный текст.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +        <a class="hotel-search-buttom" href="#" class="hotel-search-item" >ПОИСК ГОСТИНИЦЫ В седоне</a>
тут правильнее будет использовать 2 класса. Первый для того, чтобы повесить стили для кнопки, обычно это btn и второй, который у тебя hotel-search-button. 

Когда видишь элементы, у которых могут быть одинаковые стили и они по смыслу несут один и тот же смысл, только выполняют разные действия (например кнопки, ссылки, картинки мб в одном блоке) то приписывай им один класс общий, а другой уникальный, если это нужно. 

Тут в принципе даже можно просто сделать один класс btn, а позже если что добавить или поправить.

2022-10-01 15:20 UTC, nisvem commented on index.html
> +      <section class="mailing-list">
Приписка к классам "list" чаще всего используется в тегах ul, ol или там, где дальше следует список какой-то, в других случаях лучше избегать этой приписки.

2022-10-01 15:20 UTC, nisven commented on index.html
> +      <section class="mailing-list">
Чаще всего для рассылок или подписок используют subscribe.

2022-10-01 15:20 UTC, nisven commented on index.html
> +        <b class="mailing-list-item">Подпишитесь на рассылку</b>
Тут аналогично. Лучше p или h3 и класс типа mailing-title или subscribe-title

2022-10-01 15:20 UTC, nisven commented on index.html
> +        <span class="mailing-list-item">Только полезная информация и никакого спама, честное бойскаутское!</span>
Тут лучше p и класс типа mailing-text или subscribe-text

2022-10-01 15:20 UTC, nisven commented on index.html
> +        <a class="mailing-list-buttom" href="">Подписаться</a>
Форму подписки лучше вынести в отдельный блок form. 
И в него поместить input и button (a обычно для ссылок используется, тут будет лучше кнопку)

2022-10-01 15:20 UTC, nisven commented on index.html
> +        <ul class="social-networks">
Вот тут можно использовать social-list )

2022-10-01 15:20 UTC, nisven commented on index.html
> +          <li class="icone">
А тут social-item

2022-10-01 15:20 UTC, nisven commented on index.html
> +            <a class="vk" href="https://vk.com/htmlacademy">Вконтакте</a>
Ссылкам тоже лучше задать общий класс social-link

2022-10-01 15:20 UTC, nisven commented on index.html
> +            <a href="https://vk.com/htmlacademy Telegram" class="telegram">Телеграм</a>
и тут со ссылкой чет непонятно, будто не для телеграмма. 
Если ссылку не знаешь - то просто # ставь.

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +        <fieldset class="catalog-filter-group">
Тут по аналогии, как я в Инфраструктуре писал.

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +      <b>Найдено гостиниц: 38</b>
Тут заменить на p и вынести в отдельный блок или секцию верхушку каталога. Я в скрине в телеграмме отправил.

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +      <select name="hotel-selection" id="">
Тут section наверно должно было быть, но необязательно его. Тут проще просто в div обернуть

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +        <a href="#" class="button button-light">
А эти кнопки лучше в список ul обернуть и назвать его типа sort-list, sort-item и sort-link

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +        <aside>
Тут просто div или section с классом типа hostel-block, вместо aside

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +          <li class="hostel-card">
Тут я сейчас приведу пример как я карточку бы сверстал: 
```

 <li class="hotels-list-item">
            <img src="" width="135" height="90">
            <div class="hotels-item-desc">
              <h3 class="hotels-item-title"><a href="#">AMARA RESORT & SPA</a></h3>
              <p class="hotels-item-price">
                <span class="hotels-item-price-left">Гостиница</span>
                <span class="hotels-item-price-right">от 4000 Р.</span>
              </p>
              <div class="hotels-item-excerpt">
                <a href="#" class="excerpt">Подробнее</a>
                <a href="#" class="reservation">Забронировать</a>
              </div>
            </div>
            <div class="hotels-item-raiting">
              <ul class="raiting-stars-list">
                <li class="raiting-stars-item"></li>
                <li class="raiting-stars-item"></li>
                <li class="raiting-stars-item"></li>
                <li class="raiting-stars-item"></li>
              </ul>
              <span class="raiting-desc"> Рейтинг <output>8,5</output> </span>
            </div>
          </li>
```

2022-10-01 15:20 UTC, nisven commented on catalog.html
> +    <section class="mailing-list">
Тут комментарии как на главной, в принципе, можешь просто продублировать оттуда.

2022-10-01 15:29 UTC, WhiteShark23 commented on index.html
> +      <a href="index.html">Логотип</a>
Так логотип и ведет на главную страницу или всё таки поставить #

2022-10-03 17:30 UTC, nisven approved these changes

2022-10-03 17:30 UTC, nisven commented on catalog.html
>            <a class="navigation-link-current" href="index.html">Гостиницы</a>
Тут нужно чтобы было 2 класса navigation-link и navigation-link-current

2022-10-03 17:30 UTC, nisven commented on catalog.html
> +              <label class="checkbox-label" for="checkbox-pool" for="checkbox-parking">
Тут 2 for, один нужно убрать

2022-10-03 17:30 UTC, nisven commented on catalog.html
> +        <ul class="number-hotels">
Тут не понял для чего список делать, если там всего 1 элемент? 
Оставь просто <p class="number-hotels-list">Найдено гостиниц: 38</p>

2022-10-03 17:30 UTC, nisven commented on index.html
> +      <ul class="header-list header-user">
класс header-user можно тут убрать

2022-10-03 17:30 UTC, nisven commented on catalog.html
>      <section class="mailing-list">
Блок mailing нужно продублировать с главной (главная это index.html)
Он по своей сути один и тот же, на обоих страницах

```

      <section class="mailing">
        <p class="mailing-title">Подпишитесь на рассылку</p>
        <span class="mailing-info">Только полезная информация и никакого спама, честное бойскаутское!</span>
        <form action="" class="mailing-buttom">
          <input type="text">
          <input type="submit" value="Подписаться">
        </form>
      </section>
```

2022-10-03 17:30 UTC, merged